### ISSUE TITLE
Add test coverage 

### ISSUE THREAD

**Issue by helio-frota** [trustification/guac-rs#46]

**Comment by i386x** [comment]
@helio-frota Thanks for opening the issue. To not just copy-paste code from trustification repo, I will make a stand-alone `cargo` plugin and shared GitHub actions for the task first. This will probably require creating a new repo inside trustification organization (we can discuss the name here).

**Comment by helio-frota** [comment]
@i386x sounds good to me :+1:

**Comment by helio-frota** [comment]
> the logo is the svg 99.9% green

Alan will -1 this 

:trollface:

**Comment by helio-frota** [comment]
extra info I noticed when playing with cargo-llvm-cov

when installing using this github action - uses: taiki-e/install-action@cargo-llvm-cov

we can see the difference for better, so we need to avoid cargo install and to use that github action 

![2024-02-19_08-58](https://github.com/trustification/guac-rs/assets/6443576/2257fc07-28bb-44c8-9e87-6d467519c712)

**Comment by helio-frota** [comment]
@i386x the previous PR was merged https://github.com/trustification/guac-rs/issues/45, thanks @bobmcwhirter :+1: 

Now is time to see what happens with the coverage part.

And we need help from admins related to the gist / token part later (I'll create another issue for this).

**Comment by helio-frota** [comment]
The last step is here https://github.com/trustification/guac-rs/issues/61 and needs admin rights, so that we can add the badge :+1:
