### ISSUE TITLE
Update async-nats

### ISSUE THREAD

**Issue by helio-frota** [trustification/guac-rs#66]
trustification dependabot vulnerability alerts
https://gist.github.com/helio-frota/da4c1c984d12cc458f5c58e8b9201fc6

**Comment by helio-frota** [comment]
@dejanb we still can see the warning I think that is because of cyclic dependency with trustification:

```
Crate:     ed25519-dalek
Version:   1.0.1
Title:     Double Public Key Signing Function Oracle Attack on `ed25519-dalek`
Date:      2022-06-11
ID:        RUSTSEC-2022-0093
URL:       https://rustsec.org/advisories/RUSTSEC-2022-0093
Solution:  Upgrade to >=2
Dependency tree:
ed25519-dalek 1.0.1
└── nkeys 0.2.0
    └── async-nats 0.29.0
        └── guac 0.1.0
```

```
├── exporter v0.1.0 (https://github.com/trustification/trustification.git?tag=v0.1.0-nightly.9382a428#9382a428)
│   ├── anyhow v1.0.86
│   ├── clap v4.5.4 (*)
│   ├── futures v0.3.30 (*)
│   ├── guac v0.1.0 (https://github.com/trustification/guac-rs.git?rev=5b8cad8342d42072a72ef4a149348d0d86a84176#5b8cad83)
│   │   ├── anyhow v1.0.86
│   │   ├── async-nats v0.29.0  <----------------------------------------------------
│   │   │   ├── async-nats-tokio-rustls-deps v0.24.0-ALPHA.1
```

either way we need to fix here first :+1:

**Comment by dejanb** [comment]
Yeah, that makes sense. We need to update traustification as well. Maybe it's time to cut the first "release"?

**Comment by helio-frota** [comment]
Unless you want some other chore tasks before like:

* update the rust version -- same as trustify ( or 177.2 same as trustification )
* update other dependencies

![2024-05-31_08-27](https://github.com/trustification/guac-rs/assets/6443576/3949f795-034d-401d-93de-facb3c3bd477)

**Comment by helio-frota** [comment]
we have breaking changes when updating `reqwest` ^

**Comment by helio-frota** [comment]
good approach +1 

I'll take a closer look I remember a good amount of compilation errors etc.

**Comment by helio-frota** [comment]
@dejanb I suspect that is messing with the other dependency

![2024-05-31_10-44](https://github.com/trustification/guac-rs/assets/6443576/803fcb79-c486-4d62-b880-a4faccad7fa2)

https://crates.io/crates/graphql_client/0.14.0/dependencies

maybe better to wait for new graphql_client version , makes sense ?

**Comment by helio-frota** [comment]
this is the last outdated all the others got updated by the PR
